name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Botan
        run: |
          brew update
          brew install botan
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
